### ISSUE TITLE
Check headers

### ISSUE THREAD

**Issue by palcu** [govro/datagovro#10]
During the `coliberator` conference somebody from the public said to me that I should better check the headers. They used this [tool](http://cyh.herokuapp.com/cyh).

- caching
- same origin policy

Look in `nginx` and `apache2` configuration files.

Also, other CKAN instances, like [data.gov.uk](http://data.gov.uk) have the same headers so maybe check the CKAN default configurations and look if you can open a pull request.

:beer: for Nitescu

**Comment by nliplace** [comment]
Need help?

**Comment by palcu** [comment]
Don't think so. Just some config settings in `development.ini`.

**Comment by palcu** [comment]
I've configured these since last autumn. Some of the configurations are really opinionated (like no caching), but the security ones are ok.
