### ISSUE TITLE
Empty resource

### ISSUE THREAD

**Issue by avra911** [govro/datagovro#46]
The CSV file empty in these pages: https://data.gov.ro/dataset/siruta/resource/a44d555c-cbb8-443b-b721-54584c087f94?inner_span=True#null

**Comment by palcu** [comment]
Displaying the CSV with the preview in page is currently disabled. However, I am able to download the file, both on the http and the https ports.

Could you please tell me what browser are you using?

**Comment by avra911** [comment]
I am able to download the file as well, but is empty,

Version 50.0.2661.102 (64-bit) Chrome, Fedora.

**Comment by palcu** [comment]
Could you please check now?

**Comment by avra911** [comment]
:+1: 

thank you!
