### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by net4u** [govro/datagovro#57]
Salut,

Exista undeva o documentatie de utilizare a API-ului? Si o lista cu informatiile ce pot fi obtinute?

**Comment by sparcles** [comment]
Salut ! ckan.orgZi faina! 

    On Tuesday, August 30, 2016 2:38 PM, Laurentiu LAZAR <notifications@github.com> wrote:
 

 Salut,Exista undeva o documentatie de utilizare a API-ului? Si o lista cu informatiile ce pot fi obtinute?—
